name: Run Tests

on:
  pull_request:
  push:
    branches: 
        - '**'

jobs:
  test-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
          bundler-cache: true
    
      - name: Install Gems
        working-directory: WeatherAppFrontend
        run: bundle install

      - name: Run Rails Tests
        working-directory: WeatherAppFrontend
        env:
          RAILS_ENV: test
        run: bundle exec rspec spec/controllers/weather_controller_spec.rb


  test-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install Maven
        run: sudo apt-get update && sudo apt-get install -y maven

      - name: Run Java Tests
        working-directory: WeatherAppApi
        run: mvn test